export class Shared {

    public _path: any;
    public curr_path: any;
  
    public isProfileActive: any;
    
    public MESSAGE!: string;
  
    public CONTINENTS!: any;
    
    public COUNTRIES!: any;
    
    public STATES!: any;
    
    public CITIES!: any;
  
    public REQUESTTYPE!: any;
  
    public APP!: any;
  
    public DEST!: any;
  
    public APP_VERIFY!: any;
  
    public APP_VERIFY_DETAILS!: any;
  
    public shouldResetLocation$: boolean = false;
    
    public dummy = [
        {
          "id": 1,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 2,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 3,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 4,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 5,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Canceled',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 6,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 7,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 8,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 9,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 10,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 11,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 12,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 13,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 14,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 15,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 16,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 17,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 18,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 19,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 20,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 21,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 22,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 23,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 24,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 25,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 26,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 27,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 28,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 29,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 30,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 31,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 32,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 33,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 34,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 35,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 36,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 37,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 38,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 39,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 40,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 41,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 42,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 43,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        {
          "id": 44,
          "order_no": "Order #1234",
          "user": "Shade Rowe",
          "receiver": "Vincent Isaac",
          "pick_up": "19, Odunnukan Street, Yaba",
          "drop_off": "Ikeja City Mall, Lagos",
          "amount": 'N3,000.00',
          "status": 'Completed',
          "updated": '21/04/2021 09:20AM',
        },
        
    ]

    public wallet = [
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'SUCCESS',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'FAILED',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'FAILED',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'SUCCESS',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
      {
        "id": 1,
        "transaction_id": "#0812341",
        "date": "19/09/2019",
        "narration": "WALLET TOP-UP FROM FLUTTERWAVE-109203904 24,000",
        "amount": '+24.000.00',
        "status": 'PENDING',
      },
    ]

    trip_types = [
        {
            id: 1,
            name: 'Express Delivery',
            code: 'EXPRESS-TRIP'
        },
        {
            id: 2,
            name: 'Clustered Delivery',
            code: 'CLUSTERED-TRIP'
        },
        {
            id: 3,
            name: 'Inter-State Delivery',
            code: 'INTERSTATE'
        },
    ]

    orders_aggregate = [
        {
            id: 1,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 2,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 3,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 4,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 5,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 6,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 7,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 8,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 9,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 10,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 11,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
        {
            id: 12,
            order_id: '21545',
            pick_up: 'Ikeja city mall',
            drop_off: '19, Odunukan Street',
            distance: '2.00',
            items_no: '2',
            vehicle_cat: 'Minivan',
            vehicle_size: 'Medium',
            helpers: '2',
            total: 'N3,000.00'
        },
    ]

  branches = [
    {
      id: 1,
      name: 'Gbagada',
      address: '19, Odunnukan Street, Yaba',
      staff: [
        {
          id: 1,
          name: 'Smith Rowe',
          role: 'Admin',
          phone_number: '+234 810 366 7101'
        },
        {
          id: 2,
          name: 'Smith Rowe',
          role: 'Guest',
          phone_number: '+234 810 366 7101'
        },
      ]
    },
    {
      id: 2,
      name: 'Ikoyi',
      address: '19, Odunnukan Street, Yaba',
      staff: [
        {
          id: 1,
          name: 'Smith Rowe',
          role: 'Admin',
          phone_number: '+234 810 366 7101'
        },
        {
          id: 2,
          name: 'Smith Rowe',
          role: 'Guest',
          phone_number: '+234 810 366 7101'
        },
      ]
    },
    {
      id: 3,
      name: 'Victoria Island',
      address: '19, Odunnukan Street, Yaba',
      staff: [
        {
          id: 1,
          name: 'Smith Rowe',
          role: 'Admin',
          phone_number: '+234 810 366 7101'
        },
        {
          id: 2,
          name: 'Smith Rowe',
          role: 'Guest',
          phone_number: '+234 810 366 7101'
        },
      ]
    },
    {
      id: 4,
      name: 'Oshodi',
      address: '19, Odunnukan Street, Yaba',
      staff: [
        {
          id: 1,
          name: 'Smith Rowe',
          role: 'Admin',
          phone_number: '+234 810 366 7101'
        },
        {
          id: 2,
          name: 'Smith Rowe',
          role: 'Guest',
          phone_number: '+234 810 366 7101'
        },
      ]
    },
  ]

}